[".local/share/fonts/NerdFonts/MesloLG"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.tar.xz"
refreshPeriod = "168h"
include = [
  "MesloLGSNerdFont-BoldItalic.ttf",
  "MesloLGSNerdFont-Bold.ttf",
  "MesloLGSNerdFont-Italic.ttf",
  "MesloLGSNerdFont-Regular.ttf",
  "MesloLGSNerdFontMono-BoldItalic.ttf",
  "MesloLGSNerdFontMono-Bold.ttf",
  "MesloLGSNerdFontMono-Italic.ttf",
  "MesloLGSNerdFontMono-Regular.ttf",
  "MesloLGSNerdFontPropo-BoldItalic.ttf",
  "MesloLGSNerdFontPropo-Bold.ttf",
  "MesloLGSNerdFontPropo-Italic.ttf",
  "MesloLGSNerdFontPropo-Regular.ttf",

  "MesloLGSDZNerdFont-BoldItalic.ttf",
  "MesloLGSDZNerdFont-Bold.ttf",
  "MesloLGSDZNerdFont-Italic.ttf",
  "MesloLGSDZNerdFont-Regular.ttf",
  "MesloLGSDZNerdFontMono-BoldItalic.ttf",
  "MesloLGSDZNerdFontMono-Bold.ttf",
  "MesloLGSDZNerdFontMono-Italic.ttf",
  "MesloLGSDZNerdFontMono-Regular.ttf",
  "MesloLGSDZNerdFontPropo-BoldItalic.ttf",
  "MesloLGSDZNerdFontPropo-Bold.ttf",
  "MesloLGSDZNerdFontPropo-Italic.ttf",
  "MesloLGSDZNerdFontPropo-Regular.ttf",

  "MesloLGMNerdFont-BoldItalic.ttf",
  "MesloLGMNerdFont-Bold.ttf",
  "MesloLGMNerdFont-Italic.ttf",
  "MesloLGMNerdFont-Regular.ttf",
  "MesloLGMNerdFontMono-BoldItalic.ttf",
  "MesloLGMNerdFontMono-Bold.ttf",
  "MesloLGMNerdFontMono-Italic.ttf",
  "MesloLGMNerdFontMono-Regular.ttf",
  "MesloLGMNerdFontPropo-BoldItalic.ttf",
  "MesloLGMNerdFontPropo-Bold.ttf",
  "MesloLGMNerdFontPropo-Italic.ttf",
  "MesloLGMNerdFontPropo-Regular.ttf",

  "MesloLGMDZNerdFont-BoldItalic.ttf",
  "MesloLGMDZNerdFont-Bold.ttf",
  "MesloLGMDZNerdFont-Italic.ttf",
  "MesloLGMDZNerdFont-Regular.ttf",
  "MesloLGMDZNerdFontMono-BoldItalic.ttf",
  "MesloLGMDZNerdFontMono-Bold.ttf",
  "MesloLGMDZNerdFontMono-Italic.ttf",
  "MesloLGMDZNerdFontMono-Regular.ttf",
  "MesloLGMDZNerdFontPropo-BoldItalic.ttf",
  "MesloLGMDZNerdFontPropo-Bold.ttf",
  "MesloLGMDZNerdFontPropo-Italic.ttf",
  "MesloLGMDZNerdFontPropo-Regular.ttf",

  "MesloLGLNerdFont-BoldItalic.ttf",
  "MesloLGLNerdFont-Bold.ttf",
  "MesloLGLNerdFont-Italic.ttf",
  "MesloLGLNerdFont-Regular.ttf",
  "MesloLGLNerdFontMono-BoldItalic.ttf",
  "MesloLGLNerdFontMono-Bold.ttf",
  "MesloLGLNerdFontMono-Italic.ttf",
  "MesloLGLNerdFontMono-Regular.ttf",
  "MesloLGLNerdFontPropo-BoldItalic.ttf",
  "MesloLGLNerdFontPropo-Bold.ttf",
  "MesloLGLNerdFontPropo-Italic.ttf",
  "MesloLGLNerdFontPropo-Regular.ttf",

  "MesloLGLDZNerdFont-BoldItalic.ttf",
  "MesloLGLDZNerdFont-Bold.ttf",
  "MesloLGLDZNerdFont-Italic.ttf",
  "MesloLGLDZNerdFont-Regular.ttf",
  "MesloLGLDZNerdFontMono-BoldItalic.ttf",
  "MesloLGLDZNerdFontMono-Bold.ttf",
  "MesloLGLDZNerdFontMono-Italic.ttf",
  "MesloLGLDZNerdFontMono-Regular.ttf",
  "MesloLGLDZNerdFontPropo-BoldItalic.ttf",
  "MesloLGLDZNerdFontPropo-Bold.ttf",
  "MesloLGLDZNerdFontPropo-Italic.ttf",
  "MesloLGLDZNerdFontPropo-Regular.ttf",
]

[".local/share/fonts/NerdFonts/FiraCode"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz"
refreshPeriod = "168h"
include = [
  "FiraCodeNerdFont-Light.ttf",
  "FiraCodeNerdFont-Regular.ttf",
  "FiraCodeNerdFont-Retina.ttf",
  "FiraCodeNerdFont-Medium.ttf",
  "FiraCodeNerdFont-SemiBold.ttf",
  "FiraCodeNerdFont-Bold.ttf",

  "FiraCodeNerdFontMono-Light.ttf",
  "FiraCodeNerdFontMono-Regular.ttf",
  "FiraCodeNerdFontMono-Retina.ttf",
  "FiraCodeNerdFontMono-Medium.ttf",
  "FiraCodeNerdFontMono-SemiBold.ttf",
  "FiraCodeNerdFontMono-Bold.ttf",

  "FiraCodeNerdFontPropo-Light.ttf",
  "FiraCodeNerdFontPropo-Regular.ttf",
  "FiraCodeNerdFontPropo-Retina.ttf",
  "FiraCodeNerdFontPropo-Medium.ttf",
  "FiraCodeNerdFontPropo-SemiBold.ttf",
  "FiraCodeNerdFontPropo-Bold.ttf",
]
